### ISSUE TITLE
Test references most recently recreated issue, instructions say "first contact"

### ISSUE THREAD

**Issue by cyberjus** [Cloud-Code-Academy/developer-kickstart-cohort6-module5-soql-developer-kickstart-week5#2]
https://github.com/Cloud-Code-Academy/developer-kickstart-cohort6-module5-soql-developer-kickstart-week5/blob/813548415592aa7a4ad5ca1b328afe8704b58df0/force-app/main/default/classes/SOQLTest.cls#L748

Question 25

Most people seem to be trying to get only the first contact on the account. They are checking from their query they have only the first contact. This seems to be more accurate solution. This should probably be changed to testContact1

`for (Contact contact : accountContacts) {
            // Add the first contact for each account to the map
            if (!accountToContactMap.containsKey(contact.AccountId)) {
                accountToContactMap.put(contact.AccountId, contact);
            }`

**Comment by walters954** [comment]
Resolve with update to question 25
